/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED by scripts/codegen.mjs.
 *
 * To regenerate, run `pnpm --filter @skating/convex codegen` (or `npx convex dev`).
 * @module
 */

import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
