/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReackRouteImport } from './routes/reack'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MapRouteImport } from './routes/_map'
import { Route as MapIndexRouteImport } from './routes/_map.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as MapWaterIdRouteImport } from './routes/_map.water.$id'
import { Route as MapReportIdRouteImport } from './routes/_map.report.$id'
import { Route as MapHazardIdRouteImport } from './routes/_map.hazard.$id'
import { Route as MapBountyIdRouteImport } from './routes/_map.bounty.$id'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReackRoute = ReackRouteImport.update({
  id: '/reack',
  path: '/reack',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/_map',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const MapWaterIdRoute = MapWaterIdRouteImport.update({
  id: '/water/$id',
  path: '/water/$id',
  getParentRoute: () => MapRoute,
} as any)
const MapReportIdRoute = MapReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => MapRoute,
} as any)
const MapHazardIdRoute = MapHazardIdRouteImport.update({
  id: '/hazard/$id',
  path: '/hazard/$id',
  getParentRoute: () => MapRoute,
} as any)
const MapBountyIdRoute = MapBountyIdRouteImport.update({
  id: '/bounty/$id',
  path: '/bounty/$id',
  getParentRoute: () => MapRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MapIndexRoute
  '/about': typeof AboutRoute
  '/feed': typeof FeedRoute
  '/onboarding': typeof OnboardingRoute
  '/reack': typeof ReackRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/u/$username': typeof UUsernameRoute
  '/bounty/$id': typeof MapBountyIdRoute
  '/hazard/$id': typeof MapHazardIdRoute
  '/report/$id': typeof MapReportIdRoute
  '/water/$id': typeof MapWaterIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/feed': typeof FeedRoute
  '/onboarding': typeof OnboardingRoute
  '/reack': typeof ReackRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/u/$username': typeof UUsernameRoute
  '/': typeof MapIndexRoute
  '/bounty/$id': typeof MapBountyIdRoute
  '/hazard/$id': typeof MapHazardIdRoute
  '/report/$id': typeof MapReportIdRoute
  '/water/$id': typeof MapWaterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_map': typeof MapRouteWithChildren
  '/about': typeof AboutRoute
  '/feed': typeof FeedRoute
  '/onboarding': typeof OnboardingRoute
  '/reack': typeof ReackRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/u/$username': typeof UUsernameRoute
  '/_map/': typeof MapIndexRoute
  '/_map/bounty/$id': typeof MapBountyIdRoute
  '/_map/hazard/$id': typeof MapHazardIdRoute
  '/_map/report/$id': typeof MapReportIdRoute
  '/_map/water/$id': typeof MapWaterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/feed'
    | '/onboarding'
    | '/reack'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/u/$username'
    | '/bounty/$id'
    | '/hazard/$id'
    | '/report/$id'
    | '/water/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/feed'
    | '/onboarding'
    | '/reack'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/u/$username'
    | '/'
    | '/bounty/$id'
    | '/hazard/$id'
    | '/report/$id'
    | '/water/$id'
  id:
    | '__root__'
    | '/_map'
    | '/about'
    | '/feed'
    | '/onboarding'
    | '/reack'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/u/$username'
    | '/_map/'
    | '/_map/bounty/$id'
    | '/_map/hazard/$id'
    | '/_map/report/$id'
    | '/_map/water/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MapRoute: typeof MapRouteWithChildren
  AboutRoute: typeof AboutRoute
  FeedRoute: typeof FeedRoute
  OnboardingRoute: typeof OnboardingRoute
  ReackRoute: typeof ReackRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reack': {
      id: '/reack'
      path: '/reack'
      fullPath: '/reack'
      preLoaderRoute: typeof ReackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_map': {
      id: '/_map'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_map/': {
      id: '/_map/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof MapRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_map/water/$id': {
      id: '/_map/water/$id'
      path: '/water/$id'
      fullPath: '/water/$id'
      preLoaderRoute: typeof MapWaterIdRouteImport
      parentRoute: typeof MapRoute
    }
    '/_map/report/$id': {
      id: '/_map/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof MapReportIdRouteImport
      parentRoute: typeof MapRoute
    }
    '/_map/hazard/$id': {
      id: '/_map/hazard/$id'
      path: '/hazard/$id'
      fullPath: '/hazard/$id'
      preLoaderRoute: typeof MapHazardIdRouteImport
      parentRoute: typeof MapRoute
    }
    '/_map/bounty/$id': {
      id: '/_map/bounty/$id'
      path: '/bounty/$id'
      fullPath: '/bounty/$id'
      preLoaderRoute: typeof MapBountyIdRouteImport
      parentRoute: typeof MapRoute
    }
  }
}

interface MapRouteChildren {
  MapIndexRoute: typeof MapIndexRoute
  MapBountyIdRoute: typeof MapBountyIdRoute
  MapHazardIdRoute: typeof MapHazardIdRoute
  MapReportIdRoute: typeof MapReportIdRoute
  MapWaterIdRoute: typeof MapWaterIdRoute
}

const MapRouteChildren: MapRouteChildren = {
  MapIndexRoute: MapIndexRoute,
  MapBountyIdRoute: MapBountyIdRoute,
  MapHazardIdRoute: MapHazardIdRoute,
  MapReportIdRoute: MapReportIdRoute,
  MapWaterIdRoute: MapWaterIdRoute,
}

const MapRouteWithChildren = MapRoute._addFileChildren(MapRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MapRoute: MapRouteWithChildren,
  AboutRoute: AboutRoute,
  FeedRoute: FeedRoute,
  OnboardingRoute: OnboardingRoute,
  ReackRoute: ReackRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
