/**
 * Hermetic stand-in for `convex codegen`.
 *
 * `convex codegen` requires a configured deployment (a Clerk/Convex login), which
 * CI does not have — and `convex/_generated/` is (correctly) gitignored. This script
 * writes the same generated files offline so `tsc` and `convex-test` work anywhere:
 *
 *   - `dataModel.d.ts` derives the whole data model from `typeof schema`, so it never
 *     needs regenerating when the schema changes.
 *   - `server.{js,d.ts}` and `api.js` are static templates.
 *   - `api.d.ts` is derived from the function modules actually on disk, so adding or
 *     removing a `convex/*.ts` file updates the typed API automatically.
 *
 * Running `npx convex dev` locally overwrites these with the real (identical-modulo-
 * formatting) output — this is only the offline/CI path. Templates mirror
 * `convex/dist/esm/cli/codegen_templates/*`.
 */

import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const convexDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'convex')
const generatedDir = join(convexDir, '_generated')

// When a `convex.config.ts` exists, this app installs Convex *components* (D5:
// `@convex-dev/geospatial`). Component codegen has a fully-typed form that needs
// live deployment analysis — the exact thing we can't do offline — but that typing
// only benefits `components.*` call sites, and installed components (e.g. the
// geospatial client) re-apply their own precise types on top. So we emit the same
// loosely-typed `components` *stub* that `convex dev` writes before its first push
// (`componentApiStubDTS`): `componentsGeneric()` in `api.js`, `AnyComponents` in
// `api.d.ts`. The app's own `api`/`internal` stay precisely derived, as before.
const hasComponents = existsSync(join(convexDir, 'convex.config.ts'))

const header = (desc) => `/* eslint-disable */
/**
 * ${desc}
 *
 * THIS CODE IS AUTOMATICALLY GENERATED by scripts/codegen.mjs.
 *
 * To regenerate, run \`pnpm --filter @skating/convex codegen\` (or \`npx convex dev\`).
 * @module
 */
`

const SERVER_JS = `${header('Generated utilities for implementing server-side Convex query and mutation functions.')}
import {
  actionGeneric,
  httpActionGeneric,
  queryGeneric,
  mutationGeneric,
  internalActionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
} from "convex/server";

export const query = queryGeneric;
export const internalQuery = internalQueryGeneric;
export const mutation = mutationGeneric;
export const internalMutation = internalMutationGeneric;
export const action = actionGeneric;
export const internalAction = internalActionGeneric;
export const httpAction = httpActionGeneric;
`

const SERVER_DTS = `${header('Generated utilities for implementing server-side Convex query and mutation functions.')}
import {
  ActionBuilder,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  GenericDatabaseReader,
  GenericDatabaseWriter,
} from "convex/server";
import type { DataModel } from "./dataModel.js";

export declare const query: QueryBuilder<DataModel, "public">;
export declare const internalQuery: QueryBuilder<DataModel, "internal">;
export declare const mutation: MutationBuilder<DataModel, "public">;
export declare const internalMutation: MutationBuilder<DataModel, "internal">;
export declare const action: ActionBuilder<DataModel, "public">;
export declare const internalAction: ActionBuilder<DataModel, "internal">;
export declare const httpAction: HttpActionBuilder;

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;
export type DatabaseReader = GenericDatabaseReader<DataModel>;
export type DatabaseWriter = GenericDatabaseWriter<DataModel>;
`

const DATA_MODEL_DTS = `${header('Generated data model types.')}
import type {
  DataModelFromSchemaDefinition,
  DocumentByName,
  TableNamesInDataModel,
  SystemTableNames,
} from "convex/server";
import type { GenericId } from "convex/values";
import schema from "../schema.js";

export type TableNames = TableNamesInDataModel<DataModel>;
export type Doc<TableName extends TableNames> = DocumentByName<DataModel, TableName>;
export type Id<TableName extends TableNames | SystemTableNames> = GenericId<TableName>;
export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
`

const API_JS = hasComponents
  ? `${header('Generated `api` utility.')}
import { anyApi, componentsGeneric } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
export const components = componentsGeneric();
`
  : `${header('Generated `api` utility.')}
import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
`

/** Recursively list function-module paths (relative to convex/, no extension). */
function functionModules(dir = convexDir) {
  const out = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      if (entry.name === '_generated') continue
      out.push(...functionModules(full))
      continue
    }
    if (!entry.name.endsWith('.ts') || entry.name.endsWith('.d.ts')) continue
    // Skip tests, the schema, and deployment config (auth.config.ts / *.config.ts) —
    // none are function modules, matching what `convex codegen` excludes from the API.
    if (entry.name.endsWith('.test.ts') || entry.name === 'schema.ts') continue
    if (entry.name.endsWith('.config.ts')) continue
    out.push(relative(convexDir, full).replace(/\.ts$/, ''))
  }
  return out
}

// Reserved words + generated symbols that a module identifier must not collide with,
// mirroring Convex's own codegen. A clashing name gets a trailing `_`.
const RESERVED = new Set([
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'instanceof',
  'new',
  'null',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'let',
  'static',
  'yield',
  'await',
  'enum',
  'implements',
  'interface',
  'package',
  'private',
  'protected',
  'public',
  'fullApi',
  'api',
  'internal',
  'components',
])

/** Mirror Convex's `moduleIdentifier`: path → safe, collision-free JS identifier. */
function moduleIdentifier(path) {
  // Replace every non-identifier char (`/`, `-`, `.`, …) with `_`.
  let ident = path.replace(/[^a-zA-Z0-9_$]/g, '_')
  if (RESERVED.has(ident)) ident = `${ident}_`
  return ident
}

function apiDts(modules) {
  const imports = modules
    .map((m) => `import type * as ${moduleIdentifier(m)} from "../${m}.js";`)
    .join('\n')
  const entries = modules.map((m) => `  "${m}": typeof ${moduleIdentifier(m)};`).join('\n')
  // Component apps also expose a `components` handle. We keep the derived `api`/`internal`
  // typing and add only the loosely-typed stub (see `hasComponents` note above).
  const componentsImport = hasComponents
    ? 'import type { AnyComponents } from "convex/server";\n'
    : ''
  const componentsDecl = hasComponents ? '\nexport declare const components: AnyComponents;\n' : ''
  return `${header('Generated `api` utility.')}
import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
${componentsImport}${imports}

declare const fullApi: ApiFromModules<{
${entries}
}>;
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
${componentsDecl}`
}

const modules = functionModules().sort((a, b) => a.localeCompare(b, 'en-US'))

mkdirSync(generatedDir, { recursive: true })
writeFileSync(join(generatedDir, 'server.js'), SERVER_JS)
writeFileSync(join(generatedDir, 'server.d.ts'), SERVER_DTS)
writeFileSync(join(generatedDir, 'dataModel.d.ts'), DATA_MODEL_DTS)
writeFileSync(join(generatedDir, 'api.js'), API_JS)
writeFileSync(join(generatedDir, 'api.d.ts'), apiDts(modules))

console.log(`convex codegen (offline): wrote _generated for ${modules.length} modules`)
