/**
 * The **Adirondack Lakes Survey** (1984–87) — New York's only large measured-depth source (N7-2).
 *
 * ## Why this exists, and why it is a scraper
 *
 * New York is 9,422 bodies of the corpus and has had effectively no measured depth: the statewide
 * bathymetry search came back empty twice (`scripts/bathymetry/src/sources.ts`'s `NEW_YORK_STATUS`,
 * re-confirmed against the ArcGIS Hub catalogue 2026-08-08), and NYSDEC's CSLAP layer carries 278
 * lakes. The ALSC surveyed **1,469 Adirondack lakes** — 52% of the ponded waters in the region — and
 * publishes, per pond: max depth, mean depth, elevation, surface area, watershed area, littoral
 * area, shoreline length, volume and coordinates.
 *
 * **There is no bulk download.** The `.zip` files the site offers are water chemistry and long-term
 * monitoring; the 1984–87 morphometry is reachable only through a per-pond PHP report. So this is a
 * scraper, and that is a deliberate exception rather than a pattern to copy.
 *
 * ## The three things that were checked before writing it (2026-08-08)
 *
 * 1. **The TLS certificate does not validate.** It is a Let's Encrypt certificate for
 *    `www.server266.com` — a shared host that never issued one for this domain. Benign, and
 *    recorded rather than hidden: the manifest says the transport was unverified, and the payload is
 *    corroborated against data we already hold (see `corroborate`). A cross-check that agrees with
 *    GNIS names and our own polygon areas is better evidence than a certificate anyway.
 * 2. **`robots.txt` is a blanket `Disallow: /`.** Founder call, 2026-08-08: treat it as aimed at
 *    search indexers, on the ALSC's own published mission — *"for the benefit of regulatory agencies
 *    and the general public… through an exchange of objective information."* Recorded here because
 *    the next person deserves to find the reasoning, not just the code.
 * 3. **There is no licence.** Not "we did not look": every page was checked and the site publishes
 *    no terms-of-use, no data-use statement and no rights page — only a footer `copyright ©` whose
 *    year is generated by JavaScript from the current date, i.e. template boilerplate. So the honest
 *    record is *"no published terms"*, and the response to that is **attribution**, which
 *    `DEPTH_SOURCE_TERMS` carries.
 *
 * ## What the archived set actually is, measured (2026-08-08)
 *
 * **1,345 ponds, every one carrying both a max and a mean depth, zero refusals.** Internally
 * consistent — no mean deeper than its max, every coordinate inside the Adirondack box, elevations
 * 137–1,129 m. And it corroborates itself: the parsed maximum surface area is **287 ha = 709
 * acres**, against the ALSC's own prose describing a survey of lakes *"ranging in size from about
 * 0.5 to 700 acres"*. The data matches the published description of itself.
 *
 * ⚠ **That size ceiling is the honest limit of this source.** It is a survey of *small* ponds:
 * median 6 ha. Lake George, Schroon and Indian Lake are not in it, so the largest Adirondack water
 * — the water most people skate — still has no measured depth from here.
 *
 * ## Join on the NAME, never on the coordinate — measured, not assumed
 *
 * The published coordinates are DMS to the second and are **imprecise rather than merely offset**.
 * Against name-matched corpus bodies the offset has a small systematic component (~72 m north,
 * ~97 m east, about the size of a NAD27→WGS84 shift for New York) and a much larger random one
 * (**sd ~340 m**, median error 289 m). A pond of the median size is ~275 m across, so a datum
 * correction would recover a third of the error and leave the rest.
 *
 * The consequence is concrete: point-in-polygon matches **326** of 1,345, and a name match within
 * 2 km matches **866**.
 *
 * **What actually ships is the shared join, not a wider one for this source.** `transform.ts` emits
 * ALSC as ordinary `DepthRecord`s and `matchAndImportDepths` matches them the way it matches every
 * other source: containment first, then proximity inside `DEPTH_PROXIMITY_METERS` (500 m) with the
 * name or the area corroborating. So the ceiling here is 500 m, not the 2 km the measurement above
 * describes, and the difference is deliberate — the source with the *worst* coordinates is the last
 * one that should be handed a looser rule, and the load names every pond it declined.
 *
 * The 2 km name join remains the upgrade worth making, and it wants two things this one does not
 * have: a distance bound passed per source rather than per deployment, and `nameClaims` rather than
 * the stored name, because N7 keeps every publisher's name and ALSC's spelling may agree with OSM's
 * where the stored one is NHD's. Until then the shortfall is visible in the run row instead of
 * assumed away.
 *
 * The pure half is here and tested; the fetching, pacing and archiving is `snapshotAlsc.ts`, and
 * the read-back into the depth pipeline is `parseAlscArchive` in `transform.ts`.
 */

import { isPlausibleElevationM } from '@skating/core';

export const ALSC_BASE = 'https://www.adirondacklakessurvey.org';

/**
 * The counties the by-county form offers — how 1,469 ponds are enumerated in a dozen requests
 * rather than by walking a 2,551-option `<select>`.
 */
export const ALSC_COUNTIES = [
  'Clinton',
  'Essex',
  'Franklin',
  'Fulton',
  'Hamilton',
  'Herkimer',
  'Lewis',
  'Oneida',
  'Saratoga',
  'St. Lawrence',
  'Warren',
  'Washington',
] as const;

/** One pond's morphometry, as the report publishes it. */
export interface AlscPond {
  /** ALSC's own six-digit pond number, zero-padded — the archive key and the join's fallback. */
  pondNumber: string;
  name: string;
  county?: string | undefined;
  town?: string | undefined;
  lat?: number | undefined;
  lng?: number | undefined;
  elevationM?: number | undefined;
  surfaceAreaHa?: number | undefined;
  maxDepthM?: number | undefined;
  meanDepthM?: number | undefined;
  shorelineKm?: number | undefined;
  volumeM3?: number | undefined;
}

export function alscCountyUrl(): string {
  return `${ALSC_BASE}/fg_county.inc.php`;
}

export function alscPondUrl(pondNumber: string, name: string): string {
  const params = new URLSearchParams({ alscpond: pondNumber, pname: name });
  return `${ALSC_BASE}/alscrpt.inc.php?${params.toString()}`;
}

/**
 * Flatten the report to **one field per line**, decoding the entities this site actually emits.
 *
 * The line break is the whole trick. Every value is a `<li>Label: value</li>`, and once the markup
 * is gone the only thing separating `Max Depth (m): 1.2` from the next field is the item boundary —
 * so a parser that flattens to a single string has to guess where a value ends, and guesses wrong
 * the moment a value contains a colon (every coordinate does: `43°46'08" N` does not, but
 * `Volume(m3)` and `WA/SA ratio` sit next to fields that do). Turning `</li>` into a newline first
 * makes each field self-delimiting and the rest of this file boring.
 */
export function textOf(html: string): string {
  return html
    .replace(/<sup>[^<]*<\/sup>/gi, '')
    .replace(/<\s*(?:\/li|br\s*\/?|\/tr|\/p|\/h[1-6]|\/div)\s*>/gi, '\n')
    .replace(/<[^>]*>/g, ' ')
    .replace(/&deg;/gi, '°')
    .replace(/&quot;/gi, '"')
    .replace(/&nbsp;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&gt;/gi, '>')
    .replace(/&lt;/gi, '<')
    .replace(/&#39;|&apos;/gi, "'")
    .replace(/[^\S\n]+/g, ' ')
    .replace(/ ?\n ?/g, '\n')
    .replace(/\n{2,}/g, '\n')
    .trim();
}

/**
 * `43°46'08" N` → 43.768…, and `074°31'42" W` → **negative**.
 *
 * The hemisphere letter is the only thing carrying the sign — the degrees are published unsigned and
 * zero-padded — so a parser that ignores it puts every Adirondack pond in Kazakhstan. Returns
 * `undefined` rather than a partial reading: a coordinate is the join key, and a wrong one attaches
 * a real depth to the wrong lake, which is worse than attaching none.
 */
export function parseDms(text: string): number | undefined {
  const m = /(\d+)\s*°\s*(\d+)\s*'\s*(\d+(?:\.\d+)?)\s*"?\s*([NSEW])/i.exec(text);
  if (!m) return undefined;
  const [, d, min, sec, hemi] = m;
  const value = Number(d) + Number(min) / 60 + Number(sec) / 3600;
  if (!Number.isFinite(value)) return undefined;
  return /[SW]/i.test(hemi ?? '') ? -value : value;
}

/**
 * The value of a `Label: value` list item, or `undefined` when the field is present but blank.
 *
 * Matches **within one line** — see `textOf`. A blank field is a real and common state (the survey
 * did not measure everything at every pond) and must read as absent rather than as an empty string,
 * which would otherwise reach `Number('')` and become a very confident `0`.
 */
export function fieldValue(text: string, label: string): string | undefined {
  // Labels carry units and punctuation the caller should not have to escape by hand.
  const escaped = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const m = new RegExp(`^\\s*${escaped}\\s*:\\s*(.*)$`, 'im').exec(text);
  const value = m?.[1]?.trim();
  return value === undefined || value.length === 0 ? undefined : value;
}

function numberField(text: string, label: string): number | undefined {
  const raw = fieldValue(text, label);
  if (raw === undefined) return undefined;
  const m = /-?\d+(?:\.\d+)?/.exec(raw);
  if (!m) return undefined;
  const n = Number(m[0]);
  return Number.isFinite(n) ? n : undefined;
}

/**
 * Deepest reading we will accept, in metres.
 *
 * **Lake Champlain's 122 m is the deepest water in the region and is not in the Adirondack Park.**
 * The deepest Adirondack lake, Lake George, is ~59 m. 200 m is generous by more than three times
 * against the survey's own subject matter, which is the right direction for a backstop: it exists to
 * catch a units error or a mis-parsed field, not to adjudicate a real sounding.
 */
export const MAX_PLAUSIBLE_ALSC_DEPTH_M = 200;

/** Why a fetched report yielded no usable record. Counted apart — they mean different things. */
export type AlscRefusal =
  /** The response was not a pond report — an error page, or a pond number the site does not know. */
  | 'not-a-report'
  /** A report with no depth at all. Real: the survey did not sound every pond it visited. */
  | 'no-depth'
  /** A depth outside the plausible window, i.e. a parse or units failure rather than a lake. */
  | 'implausible';

export type AlscOutcome =
  | { readonly ok: true; readonly pond: AlscPond }
  | { readonly ok: false; readonly reason: AlscRefusal };

/**
 * One pond report → a record, or a counted refusal.
 *
 * Reads the flattened text rather than the DOM, because the page's structure is a nested `<ul>` of
 * `<li style="list-style-type:none">Label: value</li>` and the labels are stable where the markup is
 * not — this is a 2005-era template that has already survived one redesign.
 */
export function parseAlscReport(html: string, expectedPond?: string): AlscOutcome {
  const text = textOf(html);
  const name = fieldValue(text, 'Pond Name');
  const pondNumber = fieldValue(text, 'Pond #');
  if (name === undefined || pondNumber === undefined) return { ok: false, reason: 'not-a-report' };
  // The report echoes the pond number it actually served. A mismatch means the site resolved our
  // query to something else, and silently keying that under the number we asked for is how a depth
  // lands on the wrong lake.
  if (expectedPond !== undefined && pondNumber !== expectedPond) {
    return { ok: false, reason: 'not-a-report' };
  }

  const maxDepthM = numberField(text, 'Max Depth (m)');
  const meanDepthM = numberField(text, 'Mean Depth (m)');
  if (maxDepthM === undefined && meanDepthM === undefined) return { ok: false, reason: 'no-depth' };
  for (const d of [maxDepthM, meanDepthM]) {
    if (d !== undefined && (d <= 0 || d > MAX_PLAUSIBLE_ALSC_DEPTH_M)) {
      return { ok: false, reason: 'implausible' };
    }
  }
  // A mean deeper than the max is arithmetically impossible and means the two fields were read
  // across each other — the exact failure a label-based parser has, and one that looks plausible.
  if (maxDepthM !== undefined && meanDepthM !== undefined && meanDepthM > maxDepthM) {
    return { ok: false, reason: 'implausible' };
  }

  const elevationRaw = numberField(text, 'Elevation (m)');
  return {
    ok: true,
    pond: {
      pondNumber,
      name,
      county: fieldValue(text, 'County'),
      town: fieldValue(text, 'Town'),
      lat: parseDms(fieldValue(text, 'Latitude (DD°MM\'SS")') ?? ''),
      lng: parseDms(fieldValue(text, 'Longitude (DD°MM\'SS")') ?? ''),
      elevationM: isPlausibleElevationM(elevationRaw) ? elevationRaw : undefined,
      surfaceAreaHa: numberField(text, 'Surface Area (ha)'),
      maxDepthM,
      meanDepthM,
      shorelineKm: numberField(text, 'Shoreline Length (km)'),
      // `Volume(m<sup>3</sup>)` — the superscript is stripped, so the label reads `Volume(m)`.
      volumeM3: numberField(text, 'Volume(m)'),
    },
  };
}

/** A pond the county listing named, before its report has been fetched. */
export interface AlscPondRef {
  pondNumber: string;
  name: string;
}

/**
 * Pull `alscpond` / `pname` pairs out of a county listing.
 *
 * Deduped on the pond number, because a pond on a county line is listed by both of them — and the
 * whole point of enumerating by county is that twelve requests replace fifteen hundred.
 */
export function parsePondList(html: string): AlscPondRef[] {
  const out = new Map<string, AlscPondRef>();
  const re = /alscrpt\.inc\.php\?alscpond=([0-9]+)&(?:amp;)?pname=([^"'>]+)/gi;
  for (const m of html.matchAll(re)) {
    const pondNumber = m[1];
    const name = decodeURIComponent((m[2] ?? '').replace(/\+/g, ' ')).trim();
    if (!pondNumber || name.length === 0) continue;
    if (!out.has(pondNumber)) out.set(pondNumber, { pondNumber, name });
  }
  return [...out.values()];
}

/**
 * Does the scraped set agree with data we already hold? — **the answer to the bad certificate.**
 *
 * A certificate proves you are talking to the right server; it says nothing about whether the bytes
 * mean what you think. Since we could not have the first, take the second and take it properly: if
 * ALSC's surface areas agree with polygons we drew from OSM and NHD, and its names agree with the
 * federal gazetteer, then the payload is the survey it claims to be — from three publishers that
 * have never met.
 *
 * Returns the share of matched ponds whose area agrees within `toleranceRatio`. Deliberately a
 * *fraction of the comparable set*, not of everything: a pond our corpus has no counterpart for is
 * not evidence either way, and folding it in as agreement is the misleading-denominator shape the
 * depth join's coverage block was rebuilt to avoid.
 */
export function corroborate(
  ponds: readonly AlscPond[],
  known: ReadonlyMap<string, { areaSqM: number }>,
  toleranceRatio = 0.35,
): { comparable: number; agreeing: number; rate: number } {
  const SQ_M_PER_HA = 10_000;
  let comparable = 0;
  let agreeing = 0;
  for (const pond of ponds) {
    if (pond.surfaceAreaHa === undefined || pond.surfaceAreaHa <= 0) continue;
    const match = known.get(pond.pondNumber);
    if (match === undefined || match.areaSqM <= 0) continue;
    comparable++;
    const ours = match.areaSqM;
    const theirs = pond.surfaceAreaHa * SQ_M_PER_HA;
    const ratio = Math.min(ours, theirs) / Math.max(ours, theirs);
    if (ratio >= 1 - toleranceRatio) agreeing++;
  }
  return { comparable, agreeing, rate: comparable > 0 ? agreeing / comparable : 0 };
}
